- name: Fix permission on journal path.
  file:
    path: "{{ rrdcached_journal_path }}"
    state: directory
    owner: "{{ rrdcached_user }}"
    group: "{{ rrdcached_group }}"
    recurse: true
    mode: 0755

- name: Configure rrdcached defaults.
  template:
    src: etc/default/rrdcached.j2
    dest: "{{ rrdcached_config_file }}"
    mode: 0644
  notify: restart rrdcached

- name: remove rrdcached init.d
  file:
    path: "/etc/init.d/rrdcached"
    state: absent

- name: Configure rrdcached service (systemd).
  template:
    src: etc/systemd/system/rrdcached.service.j2
    dest: "/etc/systemd/system/rrdcached.service"
    mode: 0644
  notify:
    - restart rrdcached
  register: _rrdcached_service_config

- name: Enable and start rrdcached service.
  systemd:
    name: rrdcached.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Disable rrdcached.socket
  systemd:
    name: rrdcached.socket
    state: stopped
    enabled: no
    daemon_reload: yes